import { ThreadEventSchema } from "@/app/schemas/realtime"
import { orpc } from "@/lib/orpc/orpc"
import { workspaceQueryKeys } from "@/lib/query/workspace-query-keys"
import { ThreadMessages } from "@/lib/types"
import { useQueryClient } from "@tanstack/react-query"
import usePartySocket from "partysocket/react"
import { createContext, useContext, useMemo } from "react"
import { z } from "zod"

type ThreadRealtimeContextValueType = {
  send: (event: z.infer<typeof ThreadEventSchema>) => void
}

interface ThreadRealtimeProviderProps {
  workspaceId: string
  threadId: string
  children: React.ReactNode
}

const ThreadRealtimeContext =
  createContext<ThreadRealtimeContextValueType | null>(null)

export function ThreadRealtimeProvider({
  workspaceId,
  threadId,
  children,
}: ThreadRealtimeProviderProps) {
  const queryClient = useQueryClient()

  //get type from ORPC
  type ThreadListOptions = ReturnType<
    typeof orpc.message.thread.list.queryOptions
  >

  type ThreadQueryData = Awaited<ReturnType<ThreadListOptions["queryFn"]>>

  const socket = usePartySocket({
    host: "localhost:8787",
    room: `thread-${threadId}`,
    party: "chat",

    onMessage(e) {
      try {
        const parsedData = JSON.parse(e.data)

        const result = ThreadEventSchema.safeParse(parsedData)

        if (!result.success) {
          console.warn("Invalid thread event")
          return
        }

        const event = result.data

        if (event.type === "thread:reply:created") {
          const replyObj = event.payload.reply

          //Use the same key genreated by ORPC
          const listOptions = orpc.message.thread.list.queryOptions({
            input: { messageId: threadId, workspaceId },
            queryKey: workspaceQueryKeys.threadList(workspaceId, threadId),
          })

          queryClient.setQueryData<ThreadQueryData>(
            listOptions.queryKey,
            (old) => {
              if (!old) return old

              const reply = {
                reactions: Array.isArray(replyObj.reactions)
                  ? replyObj.reactions
                  : [],
                ...replyObj,
              } as ThreadQueryData["messages"][number]

              return {
                ...old, //preserve the parent and only update messages
                messages: [...old.messages, reply],
              }
            },
          )

          return
        }

        if (event.type === "thread:reaction:updated") {
          const {
            messageId,
            reactions: currentReactions,
            threadId: payloadThreadId,
          } = event.payload

          if (threadId !== payloadThreadId) return

          //Query key generated by ORPC
          const listOptions = orpc.message.thread.list.queryOptions({
            input: { messageId: threadId, workspaceId },
            queryKey: workspaceQueryKeys.threadList(workspaceId, threadId),
          })

          queryClient.setQueryData<ThreadMessages>(
            listOptions.queryKey,
            (old) => {
              if (!old) return old

              // helper to merge counts + preserve reactedByMe
              const merge = (
                prev: Array<{
                  emoji: string
                  count: number
                  reactedByMe?: boolean
                }> = [],
              ) =>
                currentReactions.map((currentR) => {
                  const prevMatch = prev.find((p) => p.emoji === currentR.emoji)
                  return {
                    emoji: currentR.emoji,
                    count: currentR.count,
                    reactedByMe: prevMatch?.reactedByMe ?? false,
                  }
                })

              //Parent message then just update the reactions
              // Parent message reactions
              if (messageId === threadId) {
                return {
                  ...old,
                  parent: {
                    ...old.parent,
                    reactions: merge(old.parent.reactions ?? []),
                  },
                }
              }

              // Reply reactions
              return {
                ...old,
                messages: old.messages.map((m) =>
                  m.id === messageId
                    ? { ...m, reactions: merge(m.reactions ?? []) }
                    : m,
                ),
              }
            },
          )
          return
        }
      } catch (error) {
        console.error("Something went wrong", error)
      }
    },
  })

  const value = useMemo<ThreadRealtimeContextValueType>(() => {
    return {
      send: (event) => {
        socket.send(JSON.stringify(event))
      },
    }
  }, [socket])

  return (
    <ThreadRealtimeContext.Provider value={value}>
      {children}
    </ThreadRealtimeContext.Provider>
  )
}

export function useThreadRealtime(): ThreadRealtimeContextValueType {
  const context = useContext(ThreadRealtimeContext)

  if (!context) {
    throw new Error(
      "useThreadRealtime must be used within a ThreadRealtimeProvider",
    )
  }

  return context
}

export function useOptionalThreadRealtime(): ThreadRealtimeContextValueType | null {
  return useContext(ThreadRealtimeContext)
}
